# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Copy the init-mongo.js script to the Docker container
COPY ./init-mongo.js /docker-entrypoint-initdb.d/

# Set environment variables for MongoDB configuration
ENV MONGO_INITDB_ROOT_USERNAME=admin00
ENV MONGO_INITDB_ROOT_PASSWORD=admin00
ENV MONGO_INITDB_DATABASE=docker-mern-mongo

EXPOSE 27017

# Start MongoDB with the entrypoint script from the base image
CMD ["mongod"]